dist: xenial

language: cpp

matrix:

  include:

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ppa:ubuntu-toolchain-r/test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_script:
    - eval "${MATRIX_EVAL}"
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 
    - sudo update-alternatives --slave /usr/bin/g++ g++ /usr/bin/g++-7 
    - sudo update-alternatives --config gcc
    
    - gcc --version
    - g++ --version
    - ld -v

script:
  - mkdir ./build/
  - cd ./build/
  - git clone https://github.com/TzuChieh/Photon-v2-ThirdParty.git

  # HACK: currently Travis's build toolchain is too old to handle pre-built binaries
  # build googletest locally and overwrite pre-builts to resolve some nasty issue
  #- git clone https://github.com/google/googletest.git
  #- cd ./googletest/
  #- mkdir ./build/
  #- cd ./build/
  #- cmake ../ -DCMAKE_BUILD_TYPE=release -DCMAKE_CXX_FLAGS="-std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0" -DCMAKE_INSTALL_PREFIX=""
  #- make -j4 DESTDIR="../../Photon-v2-ThirdParty/googletest/lib/linux/" install
  #- cd ../../

  - cmake ../ -DCMAKE_BUILD_TYPE=release
  #- make -j4 VERBOSE=1
  - make -j4