dist: trusty

language: cpp

matrix:

  include:

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

    - sudo apt-get install binutils-2.26
    - export PATH=/usr/lib/binutils-2.26/bin:${PATH}

before_script:
    - ld -v
    - g++ -v

script:
  - mkdir build
  - cd ./build/
  - git clone https://github.com/TzuChieh/Photon-v2-ThirdParty
  - cmake ../ -DCMAKE_BUILD_TYPE=release
  #- make -j4 VERBOSE=1
  - make -j4