dist: trusty
sudo: require
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - ld -v
  - gcc --version
  - g++ --version
  - gcc-7 --version
  - g++-7 --version
  - cmake --version
  - python --version
  - python3 --version

script:
  - git clone https://github.com/TzuChieh/Photon-v2-ThirdParty.git
  - bash ./setup.sh
  - mkdir -p ./build/
  - cd ./build/

  # HACK: currently Travis's build toolchain is too old to handle pre-built binaries
  # build googletest locally and overwrite pre-builts to resolve some nasty issue
  #- git clone https://github.com/google/googletest.git
  #- cd ./googletest/
  #- mkdir ./build/
  #- cd ./build/
  #- cmake ../ -DCMAKE_BUILD_TYPE=release -DCMAKE_CXX_FLAGS="-std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0" -DCMAKE_INSTALL_PREFIX=""
  #- make -j4 DESTDIR="../../Photon-v2-ThirdParty/googletest/lib/linux/" install
  #- cd ../../
  
  
  - cmake ../ -DCMAKE_BUILD_TYPE=release
  #- make -j4 VERBOSE=1
  - make -j4