sudo: require

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: gcc
      language: cpp
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
        env:
          - CC=gcc-7
          - CXX=g++-7

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      language: cpp

before_script:
  - ld -v
  - cmake --version
  - python --version
  - python3 --version

  - if [$TRAVIS_OS_NAME == linux]; then gcc --version; fi
  - if [$TRAVIS_OS_NAME == linux]; then g++ --version; fi
  - if [$TRAVIS_OS_NAME == linux]; then gcc-7 --version; fi
  - if [$TRAVIS_OS_NAME == linux]; then g++-7 --version; fi

  - if [$TRAVIS_OS_NAME == osx]; then clang --version; fi
  
script:
  - git clone https://github.com/TzuChieh/Photon-v2-ThirdParty.git
  - bash ./setup.sh
  - mkdir -p ./build/
  - cd ./build/
  
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_ENGINE_TEST=ON ../ 
  #- make -j4 VERBOSE=1
  - make -j4

  # Engine's unit test (working directory should be "./build/")
  - ./bin/EngineTest