sudo: false

os:
  - linux

dist: trusty

language: cpp

compiler:
  - gcc

addons:
  apt:

    # installing installing g++7 alongside clang fixed the
    # will upgrade the standard library

    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - mkdir build
  - cd ./build/
  - git clone https://github.com/TzuChieh/Photon-v2-ThirdParty
  - cmake ../ -DCMAKE_BUILD_TYPE=release
  - make -j4