sudo: require

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: gcc
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="export CC=gcc-7 && export CXX=g++-7"

    # Xcode 6.4 (6E35b)
    # Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    # Target: x86_64-apple-darwin14.3.0
    # Thread model: posix
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      language: cpp
      env:
        - MATRIX_EVAL=""

install:
  # manually install python3 since Travis does not support python on osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3; fi

before_script:
  - eval "${MATRIX_EVAL}"

  - ld -v
  - cmake --version
  - python --version
  - python3 --version

  - if [ $TRAVIS_OS_NAME == linux ]; then gcc --version; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then g++ --version; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then gcc-7 --version; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then g++-7 --version; fi

  - if [$TRAVIS_OS_NAME == osx]; then clang --version; fi
  
script:
  - git clone https://github.com/TzuChieh/Photon-v2-ThirdParty.git
  - bash ./setup.sh
  - mkdir -p ./build/
  - cd ./build/
  
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_ENGINE_TEST=ON ../ 
  #- make -j4 VERBOSE=1
  - make -j4

  # Engine's unit test (working directory should be "./build/")
  - ./bin/EngineTest